import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../app/globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Header from '@/app/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Money Tracker app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = typeof metadata.title === 'string' ? metadata.title : 'Money Tracker app';
  const description = metadata.description ?? 'Generated by create next app';

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{title}</title>
        <meta name="description" content={description} />
      </head>
      <body className={inter.className}>
        <Header title="Dashboard" user="Ilyas Abduttawab" status="Premium" />
        {children}
      </body>
    </html>
  );
}